#!/bin/bash

## #ddev-generated
## Description: Launch the storybook website.
## Usage: storybook [flags]
## Example: "ddev storybook" or "ddev storybook start"

# Define and execute command to start Storybook server
startStorybookServer () {
  # Command used to start storybook server
  command="ddev npm run storybook -- --no-open"

  # If 'yarn.lock' exists, we'll assume dev wants to use yarn package manager.
  if test -f ./yarn.lock; then
    command="ddev yarn storybook -- --no-open"
  fi

  $command;
  exit 0;
}

# Open storybook in prefered browser. This assumes the server is running
launch () {
  ddev launch :6006
}


while [ $# -gt 0 ]; do
  case "$1" in
  -s | --start)
    startStorybookServer
    shift
    ;;
  esac
  shift
done

launch
